Models/Bug.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using BugTrack.Models;

namespace BugTrack.Models
{
    public class Bug
    {
        public int Id { get; set; }
        public Severity BugSeverity { get; set; }
        public string Component { get; set; }
        [Required]
        public int projectId { get; set; }
        public string projectName { get; set; }
        [Display(Name = "Bug Description")]
        public string BugDescription { get; set; }
        public Boolean Resolved { get; set; }
        [NotMapped]
        public virtual User AssocUser { get; set; }

    }

    public enum Severity
    {
        One = 1,
        Two = 2,
        Three = 3,
        Four = 4
    }
}

Controllers/BugsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BugTrack.Models;
using BugTrack.ViewModels;

namespace BugTrack.Controllers
{
    public class BugsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext(); 

        // GET: Bugs
        [AllowAnonymous]
        public async Task<ActionResult> Index()
        {
            if (User.IsInRole("CanManageProjects"))
            {
                return View("Index", await db.Bugs.ToListAsync());
            }
            return View("RestrictedAccessIndex", await db.Bugs.ToListAsync()); 
        }

        // GET: Bugs/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bug bug = await db.Bugs.FindAsync(id);
            if (bug == null)
            {
                return HttpNotFound();
            }
            return View(bug);
        }

        // GET: Bugs/Create
        //[Route("Home")]
        public async Task<ActionResult> CreateFromProject(int? id)
        {

            Bug bugNew = new Bug();
            Project project = await db.Projects.FindAsync(id);
            //var severity = db.Severity.ToList();

            NewBugViewModel newBugViewModel = new NewBugViewModel
            {
                Bug = bugNew,
                Project = project,
                //Severities = severity,
            };

            newBugViewModel.Bug.projectId = project.Id;

            return View(newBugViewModel);
        }

        // POST: Bugs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Severity,Component,BugDescription,Resolved")] Bug bug)
        {

            if (ModelState.IsValid)
            {
                db.Bugs.Add(bug);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(bug);
        }

        // POST: Bugs/CreateFromProject
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SubmitBugFromProject([Bind(Include = "Severities,User,Project,Bug")] NewBugViewModel newBugViewModel)
        {
            Bug bug = newBugViewModel.Bug;
            if (ModelState.IsValid)
            {
                db.Bugs.Add(bug);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(bug);
        }

        // GET: Bugs/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bug bug = await db.Bugs.FindAsync(id);
            if (bug == null)
            {
                return HttpNotFound();
            }
            return View(bug);
        }

        // POST: Bugs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Severity,Component,BugDescription,Resolved")] Bug bug)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bug).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(bug);
        }

        // GET: Bugs/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Bug bug = await db.Bugs.FindAsync(id);
            if (bug == null)
            {
                return HttpNotFound();
            }
            return View(bug);
        }

        // POST: Bugs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Bug bug = await db.Bugs.FindAsync(id);
            db.Bugs.Remove(bug);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Bugs/Create.cshtml
@model BugTrack.Models.Bug

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bug</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.BugSeverity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BugSeverity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BugSeverity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Component, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Component, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Component, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BugDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BugDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BugDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Resolved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Resolved)
                    @Html.ValidationMessageFor(model => model.Resolved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Bugs/CreateFromProject.cshtml
@using BugTrack.Models

@model BugTrack.ViewModels.NewBugViewModel

@{
    ViewBag.Title = "CreateFromProject";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Submit Bug</h2>

@using (Html.BeginForm("SubmitBugFromProject", "Bugs"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Bug.projectId)

<div class="form-horizontal">
    <h4 style="text-decoration: underline;">
        @Html.DisplayNameFor(model => model.Project.ProjectName)
        <a>: </a>
        @Html.DisplayFor(model => model.Project.ProjectName)
    </h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Bug.Component, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Bug.Component, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Bug.Component, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bug.BugDescription, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Bug.BugDescription, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Bug.BugDescription, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bug.BugSeverity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Bug.BugSeverity, new SelectList(Enum.GetValues(typeof(Severity))), "Select Severity")
            @Html.ValidationMessageFor(model => model.Bug.BugSeverity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bug.Resolved, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Bug.Resolved)
                @Html.ValidationMessageFor(model => model.Bug.Resolved, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Bugs/Delete.cshtml
@model BugTrack.Models.Bug

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bug</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BugSeverity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BugSeverity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Component)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Component)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BugDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BugDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resolved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resolved)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Bugs/Details.cshtml
@model BugTrack.Models.Bug

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Bug</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BugSeverity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BugSeverity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Component)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Component)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BugDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BugDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resolved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resolved)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Bugs/Edit.cshtml
@model BugTrack.Models.Bug

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bug</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.BugSeverity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                    @*@Html.DropDownListFor(o => o.BugSeverity, Enum.GetValues(typeof(int)).Cast<int>().Select(x => new SelectListItem { Text = x.ToString(), Value = ((int)x).ToString() }))*@
                    @Html.EditorFor(model => model.BugSeverity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BugSeverity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Component, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Component, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Component, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BugDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BugDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BugDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Resolved, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Resolved)
                    @Html.ValidationMessageFor(model => model.Resolved, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Bugs/Index.cshtml
@model IEnumerable<BugTrack.Models.Bug>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table id="bugs" class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BugSeverity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Component)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BugDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Resolved)
        </th>
        <th>
            Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BugSeverity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Component)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BugDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Resolved)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-sm btn-warning" })
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-sm btn-info" })
                @*@Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-sm btn-danger js-delete" })*@
                <button data-bug-id="@item.Id" class="btn btn-sm btn-danger js-delete">Delete</button>
            </td>
        </tr>
    }

</table>


@section scripts
    {
    <script>
        $(document).ready(function () {
            $("#bugs .js-delete").on("click", function () {
                var button = $(this);
                bootbox.confirm("Are you shure you want to delete this bug?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/bugapi/" + button.attr("data-bug-id"),
                            method: "DELETE",
                            success: function () {
                                button.parents("tr").remove();
                            }
                        });
                    }
                });
            });
        });
    </script>
}

Views/Bugs/RestrictedAccessIndex.cshtml
@model IEnumerable<BugTrack.Models.Bug>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Bugs</h2>

<table id="bugs" class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BugSeverity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Component)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BugDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Resolved)
        </th>
        <th>
            Actions
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BugSeverity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Component)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BugDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Resolved)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id }, new { @class = "btn btn-sm btn-info" })
            </td>
        </tr>
    }

</table>